[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
engine = { path = "../engine" }
generator = { path = "../generator" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "book"
harness = false

[[bench]]
name = "workloads"
harness = false